import { dealCard } from "../utils/dealCard.js";
import { dealToPlayers } from "../utils/dealToPlayers.js";
export function createPlayers(deck) {
  const players = [
    {
      id: 1,
      name: "Player 1",
      hand: [],
      chips: 1000,
      bet: 0,
      timesPlayed: 0,
      fold: false,
      allIn: false,
      out: false,
      allPlays: ["call"],
      bestHand: "Unknown",
      rank: "Unknown",
    },
    {
      id: 2,
      name: "Player 2",
      hand: [],
      chips: 1000,
      bet: 0,
      timesPlayed: 0,
      fold: false,
      allIn: false,
      out: false,
      allPlays: [],
    },
    {
      id: 3,
      name: "Player 3",
      hand: [],
      chips: 1000,
      bet: 0,
      timesPlayed: 0,
      fold: false,
      allIn: false,
      out: false,
      allPlays: [],
    },
    {
      id: 4,
      name: "Player 4",
      hand: [],
      chips: 1000,
      bet: 0,
      timesPlayed: 0,
      fold: false,
      allIn: false,
      out: false,
      allPlays: [],
    },
    {
      id: 5,
      name: "Player 5",
      hand: [],
      chips: 1000,
      bet: 0,
      timesPlayed: 0,
      fold: false,
      allIn: false,
      out: false,
      allPlays: [],
    },
    {
      id: 6,
      name: "Player 6",
      hand: [],
      chips: 1000,
      bet: 0,
      timesPlayed: 0,
      fold: false,
      allIn: false,
      out: false,
      allPlays: [],
    },
  ];
  dealToPlayers(players, deck);
  return players;
}
